name: WorldUtils
version: ${project.version}
main: me.frauenfelderflorian.worldutils.WorldUtils
api-version: 1.17
authors: [ flopsi_ ]
description: a Minecraft Spigot plugin with some general handy commands
commands:
  position:
    description: save, view, delete positions
    usage: /<command> <name> | (<option> [<name>])
    aliases: pos
  personalposition:
    description: save, view, delete personal positions
    usage: /<command> <name> | (<option> [<name>])
    aliases:
      - personalpos
      - perspos
      - ppos
  sendposition:
    description: send your position to other players
    usage: /<command> [<playername>]
    aliases:
      - sendpos
      - spos
  timer:
    description: control the ingame timer
    usage: /<command> (visible | running | reverse | reset | (set | add) [[[<d>] <h>] <min>] <s>)
    aliases: tmr
  reset:
    description: reset the server
    usage: /<command> [confirm]
  settings:
    description: edit settings of this plugin
    usage: /<command> <commandname> <setting> (true | false)
    aliases: stg
