name: WorldUtils
version: ${project.version}
main: me.frauenfelderflorian.worldutils.WorldUtils
api-version: 1.17
authors: [ flopsi_ ]
description: a Minecraft Spigot plugin with some general handy commands
commands:
  position:
    description: save, view, delete positions
    usage: /<command> <name> | <option> [<name>]
    aliases: pos
  personalposition:
    description: save, view, delete personal positions
    usage: /<command> <name> | <option> [<name>]
    aliases:
      - personalpos
      - perspos
      - ppos
  reset:
    description: reset the world
    usage: /<command> [confirm]
  settings:
    description: edit settings of this plugin
    usage: /<command> <commandname> <setting> <value>
    aliases: stg
